import {
  Bolt,
  Building2,
  Lightbulb,
  Mail,
  MapPin,
  MonitorSmartphone,
  Network,
  Phone,
  PhoneCall,
  Radio,
  Search,
  ShieldCheck,
  Smartphone,
  Snowflake,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  bolt: Bolt,
  building: Building2,
  lightbulb: Lightbulb,
  mail: Mail,
  "map-pin": MapPin,
  "monitor-smartphone": MonitorSmartphone,
  network: Network,
  phone: Phone,
  "phone-call": PhoneCall,
  radio: Radio,
  search: Search,
  shield: ShieldCheck,
  smartphone: Smartphone,
  snowflake: Snowflake,
  zap: Zap,
};
